### ISSUE TITLE
Description is wrong?

### ISSUE THREAD

**Issue by misilot** [bywatersolutions/koha-plugin-rolling-hard-due-dates#2]
I think the description in the README is wrong?

> This plugin is meant to provide an easy way of reporting support issues in Koha. Once installed, it is  accessable via a button in the lower right hand corner of the screen. Clicking on the button opens a slide-in panel which allows the user to fill in support information.

It talks about reporting support issues

**Comment by kidclamp** [comment]
Fixed by commit 8da838c4679ecb2fa9a09c935ef359894f4fef8e
